   <!--Footer-->
    <footer class="page-footer center-on-small-only mt-5">

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-3">
                    <h5 class="title">Ressources </h5>
                </div>
                <!--/.First column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Second column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">Blog</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

            </div>
        </div>

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2018 Copyright: <a href="http://www.flowux.io"> ProBonoCorpo </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
	
    <!-- Font Awesome -->
	<script defer src="<?php echo $this->basePath('/js/fontawesome-all.js') ?>"></script>

    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/jquery-3.3.1.min.js') ?>"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/popper.min.js') ?>"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/bootstrap.min.js') ?>"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/mdb.min.js') ?>"></script>

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
