<html>
<head>
<style>
/* Tooltip container */
.ppittooltip {
    position: relative;
    display: inline-block;
    border-bottom: 1px dotted black; /* If you want dots under the hoverable text */
}

/* Tooltip text */
.ppittooltip .tooltiptext {
    visibility: hidden;
    width: 300px;
    background-color: orange;
    color: #fff;
//    text-align: center;
    padding: 5px 10px;
    border-radius: 6px;
 
    /* Position the tooltip text - see examples below! */
    position: absolute;
    z-index: 1;
   top: -5px;
    left: 105%; 
}
.ppittooltip .tooltiptext::after {
    content: " ";
    position: absolute;
    top: 10%; /* At the bottom of the tooltip */
    right: 100%;
    margin-top: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: transparent orange transparent transparent;
}
/* Show the tooltip text when you mouse over the tooltip container */
.ppittooltip:hover .tooltiptext {
    visibility: visible;
}
</style>

</head>
<body>
<div>&nbsp;</div>
<div>&nbsp;</div>
<!--First tooltip-->
<div class="tooltip">Hover over me
  <span class="tooltiptext">
		        <strong>Student list</strong><br>
		        As a default, all the currently registered students are presented in the list.<br><br>
		        As soon as a criterion below is specified, the list switch in search mode.
  </span>
</div>
</body>
</html>