<div style="width: 100%; height: 40; background-color: <?php echo $context->getConfig('headerParams')['background-color'] ?>; border-radius: 8px; display: block">
	<?php for ($i=0; $i < $context->getConfig('headerParams')['shift']; $i++) echo '&nbsp;' ?>

<?php if (!isset($homePage) || !$homePage) : ?>
	<a href="<?php echo $context->getConfig('headerParams')['logo-href'] ?>" rel="follow">
<?php endif;?>
		<img height="<?php echo $context->getConfig('headerParams')['logo-height'] ?>" src="<?php echo $this->basePath('/logos/'.$context->getInstance()->caption.'/'.$context->getConfig('headerParams')['logo']) ?>" alt="<?php echo $context->getInstance()->caption ?> logo" />
<?php if (!isset($homePage) || !$homePage) : ?>
	</a>
<?php endif;?>
<?php if ($context->getConfig('headerParams')['signature']) : ?>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<img width="<?php echo $context->getConfig('headerParams')['signature-width'] ?>" style="margin-left: auto; margin-right: auto" src="<?php echo $this->basePath('/logos/'.$context->getInstance()->caption.'/'.$context->getConfig('headerParams')['signature']) ?>" alt="<?php echo $context->getInstance()->caption ?> baseline" />
<?php endif;?>
</div>

<?php if ($context->isAuthenticated() && $context->getInstance()->id && $context->getInstance()->status != 'accepted') : ?>
<div class="alert alert-danger" style="text-align: center">
	<strong>
		<?php echo $this->translate('Please sign the ethical charter, prior to use P-Pit services with real data and/or give acces to real users.', null, $context->getLocale())?><br>
		<?php echo $this->translate('Access to the ethical charter:', null, $context->getLocale())?> <a href="<?php echo $this->url('instance/accept') ?>" rel="nofollow"><?php echo $this->translate('Please click here', 'ppit-core', $context->getLocale()) ?></a>
		<br>
	</strong>
</div>
<?php endif;?>

<?php if ($context->getInstance()->caption == 'Démo') : ?>
<div class="alert alert-success" style="text-align: center">
	<strong>
		<?php echo $this->translate('You\'re in demo mode. Updates are note saved in database.', null, $context->getLocale())?><br>
		<?php echo $this->translate('Just hover on the question marks', null, $context->getLocale())?> <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		<?php echo $this->translate('you will be guided for quick handling.', null, $context->getLocale())?>
	</strong>
</div>
<?php elseif ($context->isDemoModeActive()) : ?>
<div class="alert alert-success" style="text-align: center">
	<strong>
		<?php echo $this->translate('You\'re in discovery mode', null, $context->getLocale())?><br>
		<?php echo $this->translate('Just hover on the question marks', null, $context->getLocale())?> <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		<?php echo $this->translate('you will be guided for quick handling.', null, $context->getLocale())?>
	</strong>
</div>
<?php endif;?>

<?php if ($context->getInstance()->caption == 'Démo') : ?>
<div>
	<button type="button" class="btn btn-danger" id="leave-demo-anchor" onclick="location_href('leave-demo-anchor', '<?php echo $this->url('ppitUser/logout') ?><?php if (isset($applicationName)) echo '?redirect='.$this->url('public/displayPage', array('directory' => 'product', 'name' => $applicationId)) ?>')">
		<span class="glyphicon glyphicon-eye-close"></span>
		Quitter la démo
	</button>
</div>
<?php endif;?>