<!DOCTYPE html>
<html lang="en">

<?php echo $this->partial('/partials/pbc-header') ?>

<main>
    
        <div class="container" id="main">
 
            <!--Section: Contact v.2-->
            <section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">

    <!--Form without header-->
    <div class="card">

        <div class="card-body mx-4">

            <div class="text-center">
                <h3 class="dark-grey-text"><strong>Je recherche une compétence</strong></h3>
            </div>
            	<h3>
<?php $i=0; foreach ($context->getConfig('pbc/skills') as $skillId => $skill) : ?>
	<?php if ($counters[$i % count($counters)]) : ?>
					<a href="<?php echo $this->url('mockup2/result').'?skills='.$skillId ?>" class="chip chip-lg <?php echo $context->getConfig('pbc/skillColors')[$skillId] ?> white-text">
					    <?php echo $context->localize($skill) ?>&nbsp;&nbsp;<span class="badge badge-pill red"><?php echo $counters[$i % count($counters)] ?></span>
					</a>
	<?php endif;?>
<?php $i++; endforeach;?>
				</h3>

            <div class="md-form">
                <input type="text" id="search-input" class="form-control">
                <label for="search-input"><i class="fa fa-search"></i></label>
            </div>

            <div class="text-center mb-3">
                <a id="search-button" href="#" type="button" class="btn blue-gradient btn-block btn-rounded z-depth-1a">Lancer la recherche</a>
            </div>

            <div class="text-center">&nbsp;</div>

            <div class="text-center">
                <a href="#contributor"><strong>J'ai des compétences à proposer</strong></a>
            </div>
        </div>
    </div>
    <!--/Form without header-->

                <!--Section heading-->
                <h2 id="contributor">&nbsp;</h2>
                <h2 class="section-heading h1 pt-4">J'ai des compétences à proposer</h2>
                <!--Section description-->
                <p class="section-description">Génial ! Nous vous remercions et serons heureux de vous accueillir dans la communauté. Nous vous invitons à vous <a href="#">enregistrer en ligne</a>. Vous pourrez importer vos compétences depuis ACE et définir vos préférences : localisation, plages horaires de disponibilité.... </p>
                <p class="section-description">Si vous souhaitez des précisions sur <em>ProBono Corpo</em>, vous pouvez nous contacter :</p>

                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-8 col-xl-9">
                        <form>

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-6">
                                    <div class="md-form">
                                        <div class="md-form">
                                            <input type="text" id="contact-name" class="form-control">
                                            <label for="contact-name" class="">Votre nom</label>
                                        </div>
                                    </div>
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-md-6">
                                    <div class="md-form">
                                        <div class="md-form">
                                            <input type="text" id="contact-email" class="form-control">
                                            <label for="contact-email" class="">Votre email</label>
                                        </div>
                                    </div>
                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <!--Grid row-->
                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-12">

                                    <div class="md-form">
                                        <textarea type="text" id="contact-message" class="md-textarea"></textarea>
                                        <label for="contact-message">Votre question</label>
                                    </div>

                                </div>
                            </div>
                            <!--Grid row-->

                        </form>

                        <div class="center-on-small-only">
                            <a class="btn btn-light-blue btn-rounded">Soumettre</a>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-4 col-xl-3">
                        <ul class="contact-icons">
                            <li><i class="fa fa-map-marker fa-2x"></i>
                                <p>Paris La Défense, France</p>
                            </li>

                            <li><i class="fa fa-phone fa-2x"></i>
                                <p>01 02 03 04 05</p>
                            </li>

                            <li><i class="fa fa-envelope fa-2x"></i>
                                <p>contact-probono@socgen.com</p>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->

                </div>

            </section> 
            <!--Section: Contact v.2-->
            
        </div>
    
    </main>
    <!--Main Layout-->

<?php echo $this->partial('/partials/pbc-footer') ?>

    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/jquery-3.2.1.min.js') ?>"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/popper.min.js') ?>"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/bootstrap.min.js') ?>"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/mdb.min.js') ?>"></script>

    <script>

        $('#search-button').click(function () {
            location.href = '<?php echo $this->url('mockup2/result') ?>' + '?skills=' + $('#search-input').val();
        });
    </script>
</body>
</html>