<?php 
$properties = $content['description']['properties'];
?>
<table class="table">
    <thead>
        <tr>
            <th>
	            <input type="checkbox" id="checkbox_contributor" class="checkbox" />
	            <label for="checkbox_contributor" class="label-table"></label>
            </th>
<?php foreach ($content['description']['list']['properties'] as $propertyId => $options) : ?>
	<?php $property = $properties[$propertyId] ?>
		<?php if ($property['type'] == 'location') : ?>
            <th><i class="fa fa-location-arrow fa-lg"></i> <?php echo $context->localize($property['labels']) ?></th>
		<?php elseif ($property['type'] == 'languages') : ?>
            <th><i class="fa fa-language fa-lg"></i> <?php echo $context->localize($property['labels']) ?></th>
		<?php elseif ($property['type'] == 'skills') : ?>
            <th><?php echo $context->localize($property['labels']) ?></th>
		<?php elseif ($property['type'] == 'photo') : ?>
            <th>&nbsp;</th>
		<?php else : ?>
            <th><?php echo $context->localize($property['labels']) ?></th>
         <?php endif?>
<?php endforeach;?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($content['data'] as $item) : ?>
        <tr>
            <td scope="row">
                <input type="checkbox" id="checkbox_<?php echo $item['id'] ?>" class="checkbox checkbox_contributor" />
                <label for="checkbox_<?php echo $item['id'] ?>" class="label-table"></label>
            </td>

	<?php foreach ($content['description']['list']['properties'] as $propertyId => $options) : ?>
		<?php $property = $properties[$propertyId] ?>

		<?php if ($property['type'] == 'select') : ?>
            <td><?php if ($item[$propertyId]) echo $context->localize($properties[$propertyId]['modalities'][$item[$propertyId]]) ?></td>

		<?php elseif ($property['type'] == 'date') : ?>
            <td><?php echo $context->decodeDate($item[$propertyId]) ?></td>

		<?php elseif ($property['type'] == 'number') : ?>
            <td><?php echo $context->formatNumber($item[$propertyId], 2) ?></td>

		<?php elseif ($property['type'] == 'photo') : ?>
            <td>
				<span class="avatar mx-auto">
					<img src="<?php echo $this->basePath('photos/'.$item['photo_link_id']) ?>" width="60" alt="Second sample avatar image">
				</span>
            </td>

		<?php elseif ($property['type'] == 'skills') : ?>
            <td>
<?php foreach ($item[$propertyId] as $skillId => $level) : ?>
				<span class="chip <?php echo $context->getConfig('pbc/skillColors')[$skillId] ?> white-text">
				    <?php echo $context->localize($context->getConfig('pbc/skills')[$skillId]) ?>&nbsp;&nbsp;<span class="badge badge-pill red"><?php echo $level ?></span>
				</span>
<?php endforeach;?>
            </td>

		<?php elseif ($property['type'] == 'location') : ?>
            <td>
				<span class="chip danger-color white-text">
				    <?php echo $context->localize($context->getConfig('pbc/locations')[$item[$propertyId]]) ?>
				</span>
			</td>

		<?php elseif ($property['type'] == 'multiselect') : ?>
            <td>
<?php foreach ($property['modalities'] as $key => $labels) : ?>
	<?php if (in_array($key, $item[$propertyId])) : ?>
				<span class="chip teal lighten-2 white-text">
				    <?php echo $context->localize($labels) ?>
				</span>
	<?php endif;?>
<?php endforeach;?>
			</td>

		<?php else : ?>
            <td><?php echo $item[$propertyId] ?></td>

        <?php endif;?>
	<?php endforeach;?>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
