<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>ProBono Corpo</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo $this->basePath('/font-awesome-4.7.0/css/font-awesome.min.css') ?>">

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->basePath('MDB Pro/css/bootstrap.min.css" rel="stylesheet') ?>">

    <!-- Material Design Bootstrap -->
    <link href="<?php echo $this->basePath('MDB Pro/css/mdb.min.css" rel="stylesheet') ?>">

    <!-- Your custom styles (optional) -->
    <link href="<?php echo $this->basePath('MDB Pro/css/style.css" rel="stylesheet') ?>">


    <style>
        
        .top-nav-collapse {
            background-color: #9da4b1 !important; 
        }
        .navbar:not(.top-nav-collapse) {
            background: transparent !important;
        }
        @media (max-width: 768px) {
            .navbar:not(.top-nav-collapse) {
                background: #9da4b1 !important;
            } 
        }
        @media (max-width: 740px) {
            .full-height,
            .full-height body,
            .full-height header,
            .full-height header .view {
                height: 700px; 
            } 
        }
        footer.page-footer {
            background-color: #9da4b1;
        }
           
    </style>
</head>

<body>

    <!--Main Navigation-->
    <header>

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
            <div class="container">
				<a href="<?php echo $this->url('mockup/landingPage') ?>" class="navbar-brand"><img height="<?php echo $context->getConfig('bootstrap4')['logo-height'] ?>" src="<?php echo $this->basePath('/logos/'.$context->getInstance()->caption.'/'.$context->getConfig('bootstrap4')['logo']) ?>" alt="<?php echo $context->getInstance()->caption ?> logo" /></a>
                <a href="<?php echo $this->url('mockup/landingPage') ?>" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-7" aria-controls="navbarSupportedContent-7" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-user"></i> S'enregistrer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <!--Main Navigation-->


  <!--Main layout-->
  <main>
    <div class="container">
<br><br><br><br>
		
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

<?php foreach ($accounts as $account) : ?>

            <!--Grid column-->
            <div class="col-lg-7 col-md-12 mb-4">

                <div class="col-md-6 float-left">
                    <div class="avatar mx-auto">
                        <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(20).jpg" class="rounded img-fluid z-depth-1" alt="Second sample avatar image">
                    </div>
                </div>

                <div class="col-md-6 float-right">
                    <h4>
                        <strong><?php echo $account['n_first'] ?></strong>
                    </h4>
                    <h6 class="font-weight-bold grey-text mb-4">
                    	<i class="fa fa-location-arrow fa-lg"></i> <?php echo $context->localize($context->getConfig('pbc/locations')[$account['location']]) ?>
                    	&mdash;
                    	<i class="fa fa-language fa-lg"></i> <?php echo $context->localize($context->getConfig('pbc/languages')[$account['language']]) ?>
                    </h6>
					<hr>
					<h6>
	<?php foreach ($account['json_property_1'] as $skillId => $skill) : ?>
						<span class="chip chip-lg <?php echo $context->getConfig('pbc/skillColors')[$skillId] ?> white-text">
						    <?php echo $context->localize($context->getConfig('pbc/skills')[$skillId]) ?>&nbsp;&nbsp;<span class="badge badge-pill red"><?php echo $skill ?></span>
						</span>
	<?php endforeach;?>
					</h6>
					<hr>
					<p class="grey-text">
	<?php foreach ($account['availability'] as $row) : ?>
						<?php echo $row ?><br>
	<?php endforeach;?>
					</p>
					<hr>
                    <!--Facebook-->
                    <a class="icons-sm fb-ic">
                        <i class="fa fa-linkedin"> </i>
                    </a>
                </div>

            </div>
            <!--Grid column-->
<?php endforeach;?>

            <!--Grid column-->
            <div class="col-lg-5 col-md-12 mb-4">

<!-- Card -->
<div class="card sticky">

    <!-- Card body -->
    <div class="card-body">

        <!-- Material form register -->
        <form>
			<button id="begin" type="button" class="btn btn-secondary waves-effect datepicker">26/03/2018 - 30/03/2018</button>
			<button id="duration" type="button" class="btn btn-outline-secondary waves-effect datepicker">Durée</button>
			<hr>
            <div class="text-center py-4 mt-3">
                <button class="btn btn-danger" type="submit">Vérifier la disponibilité</button>
            </div>
        </form>
        <!-- Material form register -->

    </div>
    <!-- Card body -->

</div>
<!-- Card -->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

    </div>
  </main>
  <!--Main layout-->
  
    <!--Footer-->
    <footer class="page-footer center-on-small-only mt-5">

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-3">
                    <h5 class="title">Ressources </h5>
                </div>
                <!--/.First column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Second column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">Blog ProBonoCorpo</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Third column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">Culture & Conduct</a></li>
                    </ul>
                </div>
                <!--/.Third column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Fourth column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">ACE</a></li>
                    </ul>
                </div>
                <!--/.Fourth column-->

            </div>
        </div>

        <hr>

        <div class="container">
            <!--Grid row-->
            <div class="row mb-3">

                <!--First column-->
                <div class="col-md-12">

                    <ul class="list-unstyled d-flex justify-content-center mb-0 py-4">
                        <li><a class="icons-sm tw-ic"><i class="fa fa-twitter white-text fa-lg"> </i></a></li>
                        <li><a class="icons-sm li-ic"><i class="fa fa-linkedin white-text fa-lg"> </i></a></li>
                    </ul>

                </div>
                <!--/First column-->
            </div>
            <!--/Grid row-->
        </div>
        <!--/.Footer Links-->

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2018 Copyright: <a href="http://www.flowux.io"> SOCIETE GENERALE </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/jquery-3.2.1.min.js') ?>"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/popper.min.js') ?>"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/bootstrap.min.js') ?>"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/mdb.min.js') ?>"></script>

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>


<script>

$(function () {
    $(".sticky").sticky({
        topSpacing: 90
        , zIndex: 2
        , stopper: "#YourStopperId"
    });
});

$(document).ready(function() {
	// Initialize Material Select
	$('.mdb-select').material_select();
});

$('#update').on('click', function() {
	// This will select 2nd option
	$('.select-dropdown li:eq( 2 )').trigger('click');
});
</script>

</body>

</html>