<!DOCTYPE html>
<html lang="en">

<!-- Header -->
<?php echo $this->partial('/partials/pbc-header') ?>

<div class="container" id="main">
	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">
		<div>&nbsp;</div>
		<div class="row public-text">
			<div class="col-md-4">
				<div class="view overlay hm-white-light z-depth-1-half">
					<img src="<?php echo $this->basePath('/img/flux/tour-eiffel.jpg') ?>" class="img-fluid " alt="Tour Eiffel" />
						<div class="mask"></div>
				</div>
			</div>
		
			<div class="col-md-8" id="document_part_panel_0">			
				<div class="card-block">
					<h3>Les compétences en libre-service</h3>
					<hr>
					<p><i class="far fa-lg fa-question-circle text-danger"></i>&nbsp;&nbsp;Vous avez des <span class="font-weight-bold text-secondary">compétences</span> à proposer ou demander ponctuellement ?</p>
					<p><i class="far fa-lg fa-question-circle text-danger"></i>&nbsp;&nbsp;Vous seriez prêt à consacrer un peu de temps pour donner un <span class="font-weight-bold text-secondary">coup de main</span> ?</p>
					<p><i class="far fa-lg fa-question-circle text-danger"></i>&nbsp;&nbsp;Comme manager vous aimeriez inciter vos collaborateurs à <span class="font-weight-bold text-secondary">valoriser</span> dans le groupe leur <span class="font-weight-bold text-secondary">savoir-faire</span> ?</p>
					<p><i class="far fa-lg fa-check-square text-success"></i>&nbsp;&nbsp;Nous vous invitons à vous exprimer, en répondant de façon anonyme à quatre questions simples, et nous aider à rendre possible ces modes de collaboration dans le groupe <span class="font-weight-bold text-secondary">SOCIETE GENERALE</span>.</p>
					<div class="text-center"><a href="#survey" class="btn btn-primary">Participer au sondage</a></div>
				</div>
	        </div>
		</div>
	</section>
	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">
		<div class="row public-text">
			<div class="col-md-4">
				<div class="card text-center">
					<div class="card-block">
						<h4><i class="fa fa-2x fa-battery-quarter grey-text"></i></h4>
						<h4 class="card-title text-secondary">Coup de main</h4>
		                <a href="#" class="btn btn-secondary">Découvrir</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card text-center">
					<div class="card-block">
						<h4><i class="fa fa-2x fa-battery-half grey-text"></i></h4>
						<h4 class="card-title text-secondary">Coup de pouce</h4>
		                <a href="#" class="btn btn-secondary">Découvrir</a>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card text-center">
					<div class="card-block">
						<h4><i class="fa fa-2x fa-battery-three-quarters grey-text"></i></h4>
						<h4 class="card-title text-secondary">Coup de boost</h4>
						<a href="#" class="btn btn-secondary">Découvrir</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">
		<h2 class="section-heading h1 pt-4" id="survey">Participer au sondage</h2>
		<p class="section-description">
			Génial ! Nous vous remercions et serons heureux de vous accueillir dans la communauté.<br>
			Nous vous invitons à répondre à ces quatre questions simples et anonymes.
		</p>
		<div class="row">
			
			<!--Grid column-->
			<div class="col-md-8 col-xl-9">
				<form>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<input type="text" id="contact-name" class="form-control">
								<label for="contact-name" class="">Les compétences que je pourrais proposer/demander</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<input type="text" id="contact-name" class="form-control">
								<label for="contact-name" class="">Le temps que je pourrais consacrer à donner un coup de main</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Les freins pour utiliser la plateforme pour demander de l’aide / pour proposer ses compétences</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Ce qu’il faudrait éviter de faire avec cette plateforme</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Commentaire libre</label>
							</div>
						</div>
					</div>
				</form>
				<div class="center-on-small-only">
					<a class="btn btn-light-blue btn-rounded">Soumettre</a>
				</div>
			</div>
			<!--Grid column-->

			<!--Grid column-->
			<div class="col-md-4 col-xl-3">
				<ul class="contact-icons">
					<li><i class="fa fa-map-marker fa-2x"></i>
						<p>Paris La Défense, France</p>
					</li>
					<li><i class="fa fa-phone fa-2x"></i>
						<p>01 02 03 04 05</p>
					</li>
					<li><i class="fa fa-envelope fa-2x"></i>
						<p>contact-probono@socgen.com</p>
					</li>
				</ul>
			</div>
			<!--Grid column-->
		</div>
	</section> 
	<!--Section: Contact v.2-->

</div>

<!-- Footer -->
<?php echo $this->partial('/partials/pbc-footer') ?>

</html>
